# Tcl package index file, version 1.1
# This file is generated by the "pkg_mkIndex -lazy" command
# and sourced either when an application starts up or
# by a "package unknown" script.  It invokes the
# "package ifneeded" command to set up package-related
# information so that packages will be loaded automatically
# in response to "package require" commands.  When this
# script is sourced, the variable $dir must contain the
# full path name of this file's directory.

package ifneeded tclgcode 1.0 [list tclPkgSetup $dir tclgcode 1.0 {{tclgcode.tcl source {_arc _check_move_args _get_move_args _parse_arc_args clockwise_arc counterclockwise_arc cut_hole_with_radius dwell end_job finish_moves linear_move rapid_linear_move set_arc_tolerance_mm set_feedrate_timebase spindle_clockwise spindle_off use_absolute_positioning use_inches use_millimetres use_relative_positioning}}}]
